In [1]:
import torch
import numpy as np

In [2]:
a = np.random.rand(3, 128, 256)

In [3]:
np.expand_dims(a, axis=0).shape

(1, 3, 128, 256)

In [4]:
b = torch.tensor(a)

In [5]:
b.shape

torch.Size([3, 128, 256])

In [6]:
eb = b.expand(100, -1, -1, -1)

In [29]:
eb.element_size() * eb.nelement() * 10e-6

786.432

In [13]:
_vi = torch.linspace(0, 9, 10)
_vj = torch.linspace(0, 4, 5)
vj, vi = torch.meshgrid([_vj, _vi])

In [14]:
vj

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [15]:
vi

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
_qi = np.linspace(0, 9, 10)
_qj = np.linspace(0, 4, 5)
qi, qj = np.meshgrid(_qi, _qj)

In [21]:
qj

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [24]:
qi

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [31]:
np.stack((qi, qj), axis=2).shape

(5, 10, 2)

In [78]:
g = np.zeros((4,4))
j = np.random.rand(4,4)

g @ j

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
i = np.random.rand(2,3,4) + 100

In [89]:
np.floor(i)

array([[[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]],

       [[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]]])