In [1]:
import torch
import numpy as np

In [2]:
a = np.random.rand(3, 128, 256)

In [3]:
np.expand_dims(a, axis=0).shape

(1, 3, 128, 256)

In [4]:
b = torch.tensor(a)

In [5]:
b.shape

torch.Size([3, 128, 256])

In [6]:
eb = b.expand(100, -1, -1, -1)

In [29]:
eb.element_size() * eb.nelement() * 10e-6

786.432

In [13]:
_vi = torch.linspace(0, 9, 10)
_vj = torch.linspace(0, 4, 5)
vj, vi = torch.meshgrid([_vj, _vi])

In [14]:
vj

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [15]:
vi

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
_qi = np.linspace(0, 9, 10)
_qj = np.linspace(0, 4, 5)
qi, qj = np.meshgrid(_qi, _qj)

In [21]:
qj

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [24]:
qi

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [31]:
np.stack((qi, qj), axis=2).shape

(5, 10, 2)

In [78]:
g = np.zeros((4,4))
j = np.random.rand(4,4)

g @ j

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
i = np.random.rand(2,3,4) + 100

In [89]:
np.floor(i)

array([[[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]],

       [[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]]])

In [5]:
from torchvision import transforms
from PIL import Image

In [3]:
to_tensor = transforms.Compose([
    transforms.ToTensor(),
])

In [12]:
img = Image.open('./data/pano.jpg', mode='r')

In [13]:
to_tensor(img).shape

torch.Size([3, 2688, 5376])

In [21]:
a = torch.randn((4,4))
a

tensor([[ 0.0434,  0.1675,  1.0223,  0.1601],
        [ 1.5564, -1.3140,  1.7073, -0.1740],
        [-0.6718, -0.1766,  0.7759, -0.7986],
        [-0.4755, -0.2188, -0.9810,  1.8009]])

In [16]:
a.inverse()

tensor([[ 3.1279e-03,  5.3140e-01, -7.6236e-01,  3.4791e-01],
        [-8.0474e-01, -1.4487e+00, -1.5396e+00,  1.6827e+00],
        [ 9.2524e-01,  4.2295e-01, -3.5507e+00,  1.0391e+00],
        [-8.4650e-01,  3.2112e+00,  1.3084e+01, -9.3899e+00]])

In [17]:
a.dtype

torch.float32

In [22]:
a.type(torch.int64)

tensor([[ 0,  0,  1,  0],
        [ 1, -1,  1,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  1]])

In [23]:
a = [1, 2, 4]

In [24]:
j, k, l = torch.tensor(a)

In [25]:
j

tensor(1)